# Generated by Django 5.2.3 on 2025-06-24 01:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='디바이스 이름')),
                ('location', models.CharField(max_length=200, verbose_name='설치 위치')),
                ('api_key', models.CharField(max_length=255, unique=True, verbose_name='API 키')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'verbose_name': '디바이스',
                'verbose_name_plural': '디바이스들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('temperature_high', '고온 경고'), ('temperature_low', '저온 경고'), ('humidity_high', '고습도 경고'), ('humidity_low', '저습도 경고'), ('air_quality_bad', '공기질 나쁨'), ('uv_high', '자외선 강함')], max_length=20, verbose_name='알림 타입')),
                ('threshold_value', models.FloatField(verbose_name='임계값')),
                ('current_value', models.FloatField(verbose_name='현재값')),
                ('status', models.CharField(choices=[('active', '활성'), ('resolved', '해결됨'), ('ignored', '무시됨')], default='active', max_length=10, verbose_name='상태')),
                ('message', models.TextField(verbose_name='알림 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생시각')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='해결시각')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.device', verbose_name='디바이스')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_high_threshold', models.FloatField(default=35.0, verbose_name='고온 임계값')),
                ('temp_low_threshold', models.FloatField(default=5.0, verbose_name='저온 임계값')),
                ('humidity_high_threshold', models.FloatField(default=80.0, verbose_name='고습도 임계값')),
                ('humidity_low_threshold', models.FloatField(default=20.0, verbose_name='저습도 임계값')),
                ('air_quality_threshold', models.FloatField(default=500.0, verbose_name='공기질 임계값')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='이메일 알림')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='푸시 알림')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 설정',
                'verbose_name_plural': '사용자 설정들',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='온도 (섭씨)', validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(100)], verbose_name='온도')),
                ('humidity', models.FloatField(help_text='습도 (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='습도')),
                ('air_quality', models.FloatField(help_text='공기질 지수 (0-1000)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='공기질')),
                ('uv_index', models.FloatField(blank=True, help_text='자외선 지수 (0-15)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='자외선 지수')),
                ('light_level', models.FloatField(blank=True, help_text='조도 (lux)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='조도')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='측정시각')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='원시 데이터')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.device', verbose_name='디바이스')),
            ],
            options={
                'verbose_name': '센서 데이터',
                'verbose_name_plural': '센서 데이터들',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='sensors_sen_device__64c3d5_idx'), models.Index(fields=['timestamp'], name='sensors_sen_timesta_a94ae6_idx')],
            },
        ),
    ]
